# dest folder
destname: sampledestname

# file concatenation
concat:
    enabled: true
    # the file will be concatenated in the following listing order
    order:
        - src/sample1.js
        - src/sample2.js

# parameter expansion
expand:
    enabled: true
    #   <% variable %>
    prefix: "<% "
    suffix: " %>"

# code beautifier
beautifier:
    enabled: true
    # indent chracter
    indentChar: ' '
    # indent size
    indentSize: 2
    # forces CRLF at end of line
    eol: \n
    # The white line
    endWithNewLine: false
    # encoding
    convertEncoding: UTF-8

# code minifier
minify:
    enabled: true

# code checker
# *jshint outputs alerts only.
jshint:
    enabled: true
    # configuration
    rcfile: .jshintrc

# functional test
mochaTest:
    enabled: false

# jsdoc genaration
jsdoc3:
    enabled: false

# web browswer sync
browserSync:
    enabled: true
    # opens browser automatically
    open: false
    # LISTEN host
    host:
    # LISTEN port
    # please check firewalld setting
    port: 60000
    # logging level
    logLevel: info
    # log information when connection is established
    logConnections: true
    # reload browser on excuting gulp
    reloadOnRestart: true
    # server setting
    server:
        # DocumentRoot
        baseDir: ./
        indexFile:
    ui:
        # LISTEN port for admin
        port: 10001
