# 最終的にdest以下に出力されるファイル名、このままだと
# dest/sampledestname.js 
# dest/sampledestname.min.js
# の2つができる.拡張子不要
destname: sampledestname

# いずれもsrc以下を直接変更したりはしない
# src/からdest/に複製したものに対して処理するのみ

# ファイル結合設定
concat:
    # 有効・無効
    enabled: true
    # 対象と順序
    order:
        - src/sample1.js
        - src/sample2.js

# 変数展開設定
expand:
    # 有効・無効
    enabled: true
    # 例）<% variable %>
    prefix: "<% "
    suffix: " %>"

# コード整形設定
beautifier:
    enabled: true
    # インデント文字列強制
    indentChar: ' '
    # インデントサイズ強制
    indentSize: 2
    # 改行コード強制
    eol: \n
    # 最後に空白行で終わらせるか
    endWithNewLine: false
    # 文字コード強制
    convertEncoding: UTF-8

# コード圧縮設定
minify:
    # 有効・無効
    enabled: true

# コードチェック設定
# beautifierと異なりアラートあげるのみ
jshint:
    # 有効・無効
    enabled: true
    # チェック内容定義ファイル
    rcfile: .jshintrc

# ファンクショナルテスト
# tests以下に必要に応じて書く
# あまり必要性を感じない
mochaTest:
    # 有効・無効
    enabled: false

# コメントからのjsdoc生成
# docs/gen以下に作成されるGitHubのREADME.mdもバインドする
# あまり必要性を感じない
jsdoc3:
    # 有効・無効
    enabled: false

# WEBサーバー立ち上げとマルチブラウザのシンク設定
# 開発時には便利
# 設定に追加していないがプロキシも設定できる
browserSync:
    # 有効・無効
    enabled: true
    # 自動的にブラウザを起動させるか(localで動かすなら使える)
    open: false
    # host(未指定でIPなので未指定でいい)
    host:
    # LISTENポート(firewalldは要確認)
    port: 60000
    # ログレベル(info,debug,silent)
    logLevel: info
    # 接続時にログ出力
    logConnections: true
    # gulp再実行時にブラウザをリロードさせるか
    reloadOnRestart: true
    # サーバー設定
    server:
        # DocumentRoot的なこと
        baseDir: ./
        indexFile:
    # browserSyncには管理画面がついているのでそちら側の設定
    ui:
        # 管理画面LISTENポート
        port: 10001

