# 最終的なファイル名
destname: sampledestname

# ファイル結合設定
concat:
    # 有効・無効
    enabled: true
    # 対象と順序
    order:
        - src/sample1.js
        - src/sample2.js

# 変数展開設定
expand:
    # 有効・無効
    enabled: true
    # 例）<% variable %>
    prefix: "<% "
    suffix: " %>"

# コード整形設定
beautifier:
    enabled: true
    # インデント文字列強制
    indentChar: ' '
    # インデントサイズ強制
    indentSize: 2
    # 改行コード強制
    eol: \n
    # 最後に空白行で終わらせるか
    endWithNewLine: false
    # 文字コード強制
    convertEncoding: UTF-8

# コード圧縮設定
minify:
    # 有効・無効
    enabled: true

# コードチェック設定
# beautifierと異なりアラートあげるのみ
jshint:
    # 有効・無効
    enabled: true
    # チェック内容定義ファイル
    rcfile: .jshintrc

# ファンクショナルテスト
mochaTest:
    # 有効・無効
    enabled: false

# コメントからのjsdoc生成
jsdoc3:
    # 有効・無効
    enabled: false

# WEBサーバー立ち上げとマルチブラウザのシンク設定
browserSync:
    # 有効・無効
    enabled: true
    # 自動的にブラウザ起動
    open: false
    # LISTEN host
    host:
    # LISTEN port
    # firewalldは要確認
    port: 60000
    # ログレベル
    logLevel: info
    # 接続時にログ出力
    logConnections: true
    # gulp再実行時にブラウザリロード
    reloadOnRestart: true
    # サーバー設定
    server:
        # DocumentRoot
        baseDir: ./
        indexFile:
    ui:
        # 管理画面LISTENポート
        port: 10001
