# 最終的に出力されるファイル名(拡張子不要)
destname: sampledestname

# ファイル結合処理
concat:
    # 有効・無効
    enabled: true
    # ファイル結合対象と順序
    order:
        - src/sample1.js
        - src/sample2.js

# 変数展開処理
expand:
    enabled: true
    # 変数プリフィクス
    prefix: '<% '
    # 変数サフィックス
    suffix: ' %>'

# コード整形処理(差分見たいのでsrc以下は変更しない)
beautifier:
    enabled: true
    # インデント文字列統一
    indentChar: ' '
    # インデントサイズ統一
    indentSize: 2
    # 改行コード統一
    eol: \n
    # 最後に空白行で終わるか
    endWithNewLine: false
    # 文字コード統一
    convertEncoding: UTF-8

# コード圧縮処理
minify:
    # 有効・無効
    enabled: true

# コードチェック
jshint:
    # 有効・無効
    enabled: true
    # チェック内容定義ファイルパス
    rcfile: .jshintrc

# mochaでファンクショナルテスト
mochaTest:
    # 有効・無効
    enabled: true

# コメントからのjsdoc生成
jsdoc3:
    # 有効・無効
    enabled: true

# WEBサーバーの立ち上げとマルチブラウザのシンク
browserSync:
    # 有効・無効
    enabled: true
    # 自動的にブラウザを起動させるか(localで動かすなら使える)
    open: false
    # host(未指定でIPなので未指定でいい)
    host:
    # LISTENポート(firewalldは要確認)
    port: 60000
    # ログレベル(info,debug,silent)
    logLevel: info
    # 接続時にログ出力
    logConnections: true
    # gulp再実行時にブラウザをリロードさせるか
    reloadOnRestart: true
    # サーバー設定
    server:
        # DocumentRoot的なこと
        baseDir: ./
        indexFile:
    # browserSyncには管理画面がついているのでそちら側の設定
    ui:
        # 管理画面LISTENポート
        port: 10001

